# Generated by Django 5.1.5 on 2025-02-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userbio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbio',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userbio',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
