# Generated by Django 5.1.5 on 2025-01-30 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_post_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
